### ISSUE TITLE
How to get the target_site.bed file

### ISSUE THREAD

**Issue by acarmas1** [weir12/DeepEdit#6]
Hello, 

I'm interested in using DeepEdit to identify A-to-I sites in my directRNA reads. I'm running your test data set, but I realized that for the sh 1.Reads_extract.sh, a target_site.bed file is needed. I was wondering how can I get this for my own data.

I'm looking forward to hearing from you.

Best,
Camila

**Comment by weir12** [comment]
Hi,

Thank you for your interest in our project. @LongxianChen will be happy to provide further information and assistance, including the`target_site.bed` files.

Best regards,
Liang Ou

**Comment by acarmas1** [comment]
Perfect, thank you. I'm looking forward to hearing from Longxian Chen :)

**Comment by LongxianChen** [comment]
> Perfect, thank you. I'm looking forward to hearing from Longxian Chen :)

Hi, Camila

Sorry for the late reply, for we were on vacation for the International Workers' Day.

The target_site.bed file contains positional information of any 'A' site that you want to check for possible editing. 
Because DeepEdit can only predict sites that are located in trained motifs , it is important to ensure that the sites provided in the target_site.bed file are within the motifs that have been trained in order to obtain reliable prediction results.

I can provide a script to help you obtain all the positions located in motifs that have been trained in your data. Because I am currently on a trip and unable to connect to the server, so it may take two or three days before I can upload it. I will try to upload it as soon as possible if you need it.

Best regards,
Longxian Chen

**Comment by acarmas1** [comment]
Hi Longxian,

Yes, if you can help me with the script to look up for A in the trained motifs. I'll appreciate it. 

I'm highly interested in using this software for predicting A-to-I editing sites.

Thanks,
Camila

**Comment by acarmas1** [comment]
Perfect, it worked with my reference transcriptome. 

Thank you so much.

**Comment by weir12** [comment]
Problem resolved
